### ISSUE TITLE
Windows Interface "Gui"

### ISSUE THREAD

**Issue by AndrioJonatas** [victorlvl47/cvMouseDemo#1]
Hi, I don't understand programming could you make a basic executable Windows Interface "Gui" version of this for me?

**Comment by victorlvl47** [comment]
Hi thanks for writing, right now I busy but if you give a few days I can deliver. 
PS, I don't promise but I will try to squeeze it inside my schedule.

**Comment by AndrioJonatas** [comment]
Okay solved!

**Comment by AndrioJonatas** [comment]
Okay solved!
